invoices/urls.py
from django.conf.urls import url

from invoices.views import InvoiceCancel, InvoiceCombine, InvoiceDisplay

app_name = 'invoices'
urlpatterns = [
    url(r'^combine/$', InvoiceCombine.as_view(), name='combine'),
    url(r'^(?P<reference_number>[^/]+)/$', InvoiceDisplay.as_view(),
        name='display'),
    url(r'^(?P<reference_number>[^/]+)/cancel/$', InvoiceCancel.as_view(),
        name='cancel'),
]

urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'^badges/', include('badges.urls')),
    url(r'^bursary/', include('bursary.urls')),
    url(r'^front_desk/', include('front_desk.urls')),
    url(r'^invoices/', include('invoices.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^register/', include('register.urls')),
    url(r'', include('dc18.urls')),
    url(r'', include('wafer.urls')),
]

invoices/models.py
from django.conf import settings
from django.core.signing import Signer
from django.core.validators import MinValueValidator
from django.db import models
from django.dispatch import receiver
from django.urls import reverse

from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received


class Invoice(models.Model):
    STATUS_CHOICES = (
        ('new', 'Invoiced'),
        ('pending', 'Payment pending'),
        ('paid', 'Payment received'),
        ('canceled', 'Invoice canceled'),
    )

    reference_number = models.CharField(max_length=128, unique=True,
                                        null=False, blank=False)
    status = models.CharField(max_length=128, choices=STATUS_CHOICES,
                              default='new')
    date = models.DateField()

    recipient = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  related_name='invoices',
                                  on_delete=models.PROTECT)
    invoiced_entity = models.CharField(max_length=128, blank=True)
    billing_address = models.TextField()
    compound = models.BooleanField(default=False)

    transaction_id = models.CharField(max_length=128, null=False, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    signer = Signer(sep=':', salt='invoices.Invoice')

    @property
    def total(self):
        return sum(line.total for line in self.lines.all())

    @property
    def total_twd(self):
        from dc18.prices import TWD_EXCHANGE_RATE
        return self.total * TWD_EXCHANGE_RATE

    def paypal_data(self):
        data = settings.PAYPAL_DATA.copy()

        data['cmd'] = '_cart'
        data['invoice'] = settings.INVOICE_PREFIX + self.reference_number
        data['upload'] = '1'

        i = 1
        for line in self.lines.all():
            if line.quantity * line.unit_price < 0:
                discount = data.get('discount_amount_cart', 0)
                discount += - (line.quantity * line.unit_price)
                data['discount_amount_cart'] = discount
                continue
            data['item_name_%d' % i] = line.description
            data['quantity_%d' % i] = line.quantity
            data['amount_%d' % i] = line.unit_price
            i = i + 1

        return data

    def text_details(self):
        header = ('Reference', 'Description', 'Qty', 'Unit', 'Total')
        footer = ('', '', '', 'Total', str(self.total))
        lines = [
            (line.reference, line.description, line.quantity, line.unit_price,
             line.total)
            for line in self.lines.all()
        ]
        all_lines = (
            [
                header,
                ('', '', '', '', ''),
            ]
            + lines
            + [
                ('', '', '', '-------', '-------'),
                footer,
            ]
        )

        col_width = [max(len(str(x)) for x in col) for col in zip(*all_lines)]
        formats = ['{:{}}'] * 3 + ['{:>{}}'] * 2
        return "\n".join(
            ("| " + " | ".join(formats[i].format(x, col_width[i])
                               for i, x in enumerate(line)) + " |")
            for line in all_lines
        )

    def save(self, *args, **kwargs):
        # generate reference number on save
        if not self.reference_number:
            year = str(self.date.year)
            last_invoice = Invoice.objects.filter(
                reference_number__startswith=year
            ).order_by('-reference_number').first()

            if last_invoice:
                year, seqnum = last_invoice.reference_number.split('-')
                seqnum = int(seqnum, 10) + 1
            else:
                seqnum = 1

            self.reference_number = '%s-%05d' % (year, seqnum)

        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'invoices:display',
            kwargs={'reference_number': self.reference_number})

    def get_signed_url(self):
        signed_reference = self.signer.sign(self.reference_number)
        return reverse(
            'invoices:display',
            kwargs={'reference_number': signed_reference})


@receiver(valid_ipn_received)
def update_invoice_on_ipn_received(sender, **kwargs):
    ipn = sender
    paypal_data = settings.PAYPAL_DATA
    if ipn.payment_status == ST_PP_COMPLETED:
        if ipn.receiver_email != paypal_data['business']:
            return
        if not ipn.invoice.startswith(settings.INVOICE_PREFIX):
            return

        invoice_number = ipn.invoice[len(settings.INVOICE_PREFIX):]
        invoice = Invoice.objects.get(reference_number=invoice_number)
        invoice.status = 'paid'
        invoice.transaction_id = ipn.txn_id
        invoice.save()

        if invoice.compound:
            for line in invoice.lines.all():
                reference = line.reference.split('#', 1)[1]
                child_invoice = Invoice.objects.get(reference_number=reference)
                child_invoice.status = 'paid'
                child_invoice.transaction_id = ipn.txn_id
                child_invoice.save()


class InvoiceLine(models.Model):
    invoice = models.ForeignKey(Invoice, related_name='lines',
                                on_delete=models.CASCADE)
    line_order = models.IntegerField()
    reference = models.CharField(max_length=32)
    description = models.CharField(max_length=1024)
    unit_price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.IntegerField(validators=[MinValueValidator(1)])

    @property
    def total(self):
        return self.unit_price * self.quantity

    class Meta:
        unique_together = ('invoice', 'line_order')
        ordering = ('invoice', 'line_order')

    def __str__(self):
        return 'InvoiceLine(%s [%s] %d @ %.02f = %.02f)' % (
            self.reference,
            self.description,
            self.quantity,
            self.unit_price,
            self.total,
        )

invoices/forms.py
from django import forms
from django.core.signing import BadSignature

from crispy_forms.helper import FormHelper

from invoices.models import Invoice


class InvoiceForm(forms.Form):
    url = forms.URLField(
        label='URL',
        required=False,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.include_media = False

    def clean_url(self):
        url = self.cleaned_data['url']
        invalid_url_error = 'Needs to a be a valid URL for a visible invoice'

        # The URL validator should have ensured that we have enough slashes to
        # do things like this
        reference_number = url.rstrip('/').rsplit('/', 1)[1]
        signed_url = ':' in reference_number
        if signed_url:
            try:
                reference_number = Invoice.signer.unsign(reference_number)
            except BadSignature:
                raise forms.ValidationError(invalid_url_error)

        try:
            invoice = Invoice.objects.get(reference_number=reference_number)
        except Invoice.DoesNotExist:
            raise forms.ValidationError(invalid_url_error)

        if self.user != invoice.recipient and not signed_url:
            raise forms.ValidationError(invalid_url_error)

        if invoice.status != 'new':
            raise forms.ValidationError('Invoice is not unpaid')

        if invoice.compound:
            raise forms.ValidationError('This is a combined invoice, itself')

        self.invoice = invoice

        return url


class InvoiceFormset(forms.BaseFormSet):
    def clean(self):
        if any(self.errors):
            return

        invoices = []
        for form in self.forms:
            if hasattr(form, 'invoice'):
                invoices.append(form.invoice.pk)

        if len(invoices) > len(set(invoices)):
            raise forms.ValidationError('Invoices must be distinct')

        if len(invoices) < 2:
            raise forms.ValidationError(
                'At least 2 URLs need to be provided for any combining to '
                'happen.')


class CombineForm(forms.Form):
    invoiced_entity = forms.CharField(
        label='Invoiced entity',
    )
    billing_address = forms.CharField(
        label='Billing address',
        widget=forms.Textarea(attrs={'rows': 3}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.include_media = False

invoices/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.signing import BadSignature
from django.db import transaction
from django.forms.models import formset_factory
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic import DetailView, TemplateView

from paypal.standard.forms import PayPalPaymentsForm
from wafer.registration.views import redirect_profile

from invoices.forms import CombineForm, InvoiceForm, InvoiceFormset
from invoices.models import Invoice, InvoiceLine
from register.models import Attendee


class InvoiceDetailView(DetailView):
    model = Invoice
    slug_field = 'reference_number'
    slug_url_kwarg = 'reference_number'

    def get_object(self):
        invoice = super().get_object()

        if self.can_view_invoice(invoice):
            return invoice

        raise Http404()

    def can_view_invoice(self, invoice):
        user = self.request.user
        return (user.has_perm('front_desk.change_checkin')
                or invoice.recipient == user)


class InvoiceDisplay(InvoiceDetailView):
    template_name = 'invoices/invoice_detail.html'

    def get_object(self):
        self.unsign()
        return super().get_object()

    def unsign(self):
        reference_number = self.kwargs['reference_number']
        self.using_signed_url = ':' in reference_number
        if self.using_signed_url:
            try:
                reference_number = Invoice.signer.unsign(reference_number)
            except BadSignature:
                raise Http404()
            self.kwargs['reference_number'] = reference_number

    def can_view_invoice(self, invoice):
        return self.using_signed_url or super().can_view_invoice(invoice)

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        paypal_data = self.object.paypal_data()
        paypal_data['notify_url'] = self.request.build_absolute_uri(
            reverse('paypal-ipn')
        )
        paypal_data['return_url'] = self.request.build_absolute_uri()

        context_data.update({
            'form': PayPalPaymentsForm(initial=paypal_data),
            'using_signed_url': self.using_signed_url,
        })

        return context_data


class InvoiceCancel(LoginRequiredMixin, InvoiceDetailView):

    @transaction.atomic
    def post(self, request, **kwargs):
        invoice = self.get_object()
        if invoice.status == 'new':
            invoice.status = 'canceled'
            invoice.save()
            messages.success(
                self.request, 'Invoice cancelled')
        else:
            messages.warning(
                self.request, 'Only unpaid invoices can be cancelled')

        return redirect_profile(self.request)


class FormFormsetView(TemplateView):
    def get_initial(self):
        return {}

    def get_initial_formset(self):
        return []

    def get_form_kwargs(self):
        kwargs = {
            'initial': self.get_initial(),
        }
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        return kwargs

    def get_form(self):
        return self.form_class(**self.get_form_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'form_kwargs': self.get_formset_form_kwargs(),
        }
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        else:
            kwargs['initial'] = self.get_initial_formset()
        return kwargs

    def get_formset_form_kwargs(self):
        return {}

    def get_formset(self):
        Formset = formset_factory(
            self.formset_form_class, formset=self.formset_class, extra=2)
        return Formset(**self.get_formset_kwargs())

    def get_context_data(self, **kwargs):
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        if 'formset' not in kwargs:
            kwargs['formset'] = self.get_formset()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        formset = self.get_formset()
        if form.is_valid() and formset.is_valid():
            return self.forms_valid(form, formset)
        else:
            return self.forms_invalid(form, formset)

    def forms_valid(self, form, formset):
        return HttpResponseRedirect(self.get_success_url())

    def forms_invalid(self, form, formset):
        return self.render_to_response(
            self.get_context_data(form=form, formset=formset))


class InvoiceCombine(LoginRequiredMixin, FormFormsetView):
    template_name = 'invoices/combine.html'
    form_class = CombineForm
    formset_form_class = InvoiceForm
    formset_class = InvoiceFormset

    def get_initial(self):
        user = self.request.user
        initial = {
            'invoiced_entity': user.userprofile.display_name()
        }
        try:
            attendee = user.attendee
        except Attendee.DoesNotExist:
            pass
        else:
            initial['billing_address'] = attendee.billing_address
        return initial

    def get_initial_formset(self):
        return [{'url': url}
                for i, url in enumerate(self.request.GET.getlist('invoice'))]

    def get_formset_form_kwargs(self):
        return {
            'user': self.request.user,
        }

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def forms_valid(self, form, formset):
        user = self.request.user

        invoice = Invoice(
            recipient=user,
            status='new',
            compound=True,
            date=timezone.now(),
            invoiced_entity=form.cleaned_data['invoiced_entity'],
            billing_address=form.cleaned_data['billing_address'],
        )
        invoice.save()

        for i, form in enumerate(formset.forms):
            if not hasattr(form, 'invoice'):
                continue
            child_invoice = form.invoice
            InvoiceLine(
                invoice_id=invoice.id,
                line_order=i,
                reference='INV#{}'.format(child_invoice.reference_number),
                description='DebConf attendance for {}'.format(
                    child_invoice.recipient.userprofile.display_name()
                ),
                unit_price=child_invoice.total,
                quantity=1,
            ).save()

        self.reference_number = invoice.reference_number
        return super().forms_valid(form, formset)

    def get_success_url(self):
        return reverse('invoices:display',
                       kwargs={'reference_number': self.reference_number})

invoices/templates/invoices/combine.html
{% extends 'wafer/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h1>Combine Invoices</h1>
  <p>
    You can combine invoices from multiple attendees (including yourself, if
    desired) into a single invoice, to be paid together.
    To do this, you need the <b>shared</b> URL for each invoice.
  </p>
  <h2>Invoices to be combined:</h2>
  <form method="post">
    {% crispy form %}
    <div id="formset">
      {% crispy formset formset.form.helper %}
    </div>
    <input class="btn btn-info" type="button" value="Add Another Invoice" id="add-url">
    <input class="btn btn-primary" type="submit" name="submit"
           value="Generate Combined Invoice">
  </form>
{% endblock %}
{% block extra_foot %}
<script type="text/javascript">
  'use strict';
  $(function() {
    $('#add-url').on('click', function(e) {
      var forms = parseInt($('#id_form-TOTAL_FORMS').val());

      var new_name = 'form-' + forms + '-url';

      var form = $('#div_id_form-0-url').clone();
      form.attr('id', 'div_id_' + new_name);

      form.find('label').attr('for', '#id_' + new_name);

      var input = form.find('input');
      input.attr('id', 'id_' + new_name);
      input.attr('name', new_name);
      input.val('');

      form.appendTo('#formset');

      $('#id_form-TOTAL_FORMS').val(forms + 1);
    });
  });
</script>
{% endblock %}

invoices/templates/invoices/invoice_detail.html
{% extends "wafer/base.html" %}
{% block title %}{{ WAFER_CONFERENCE_NAME }} - Invoice {{ object.reference_number }}{% endblock %}
{% block content %}
{% include 'invoices/includes/invoice.html' %}
<div class="row d-print-none">
  <div class="col-md">
    {% if object.status == 'new' %}
      {% if not using_signed_url %}
        <div class="card border-info mb-3">
          <h4 class="card-header bg-info">Forward Invoice:</h4>
          <div class="card-body">
            Is somebody else going to pay this on your behalf?<br>
            Send them
            <a href="{{ object.get_signed_url }}">this URL
              <i class="fas fa-link"></i></a>.<br>
            They will be able to combine this with other invoices, and pay them in
            a single payment, if desired.
          </div>
        </div>
        <div class="card border-danger mb-3">
          <h4 class="card-header bg-danger">Danger Zone:</h4>
          <div class="card-body">
            <p>
              If you have modified your registration and the invoice is no longer
              correct, you may cancel it and re-create it.
            </p>
            <form action={% url 'invoices:cancel' reference_number=object.reference_number %} method="post">
              {% csrf_token %}
              <input type="submit" class="btn btn-warning" value="Cancel Invoice">
            </form>
          </div>
        </div>
      {% elif not object.compound %}
        <div class="card border-info mb-3">
          <h4 class="card-header bg-info">Combine Invoices:</h4>
          <div class="card-body">
            <p>
              If you want to pay for multiple invoices, together, you can combine
              them into a single invoice.
            </p>
            <a href="{% url 'invoices:combine' %}?invoice={{ view.request.build_absolute_uri|urlencode }}"
               class="btn btn-warning">Combine Invoices</a>
          </div>
        </div>
      {% endif %}
    {% endif %}
  </div>
  <div class="col-md">
    {% if object.status != 'canceled' %}
      <div class="card border-success mb-3">
        <h4 class="card-header bg-success">Payment:</h4>
        <div class="card-body">
          {% if object.status == 'new' %}
            <div class="text-center">
              {{ form.render }}
            </div>
            <p>
              <strong>Note:</strong>
              You don't need a PayPal account, they'll happily take payment from
              your card, without any account. We're just using them as a payment
              processor.
            </p>
            <p>
              At the end of the payment process, they'll try to make you create
              an account, you can click "Not Now".
            </p>
            <p>
              If you don't see a PayPal button above, and use NoScript, Request
              Policy, or some similar browser plugin, you may need to whitelist
              this site in it.
            </p>
          {% elif object.status == 'pending' %}
            <p>Waiting for PayPal payment confirmation</p>
          {% elif object.status == 'paid' %}
            <p>
              Payment received via PayPal on {{ object.last_update | date }} <br>
              PayPal transaction number {{ object.transaction_id }}
            </p>
          {% endif %}
        </div>
      </div>
    {% else %}
      <div class="card border-danger mb-3">
        <h4 class="card-header bg-danger">Cancelled!</h4>
        <div class="card-body">
          <p>Cancelled on {{ object.last_update | date }}</p>
        </div>
      </div>
    {% endif %}
    <div class="mb-3 text-right">
      <a class="btn btn-warning print-button" href="">Print</a>
    </div>
  </div>
</div>
{% endblock %}
{% block extra_foot %}
  <script type="text/javascript">
    $(function() {
      $('.print-button').click(function() {
        window.print();
      });
    });
  </script>
{% endblock %}